spring:
  datasource:
    url: jdbc:h2:mem:e-commerce
    username: akkodis
    password: er^Deqrp&JuP93@u
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  jpa:
    defer-datasource-initialization: true
    show_sql: true
  sql:
    init:
      mode: always
      data-locations: classpath*:database/import_brands.sql, classpath*:database/import_products.sql, classpath*:database/import_prices.sql