spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: akkodis
    password: er^Deqrp&JuP93@u
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect